version: "3.8"
services:
  ollama:
    image: ollama/ollama
    ports: ["11434:11434"]
    volumes: [ollama_data:/root/.ollama]

  shamba-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8002:8002"]
    depends_on: [ollama]
    environment:
      - GROQ_API_KEY=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

  ccs-health:
    build:
      context: .
      dockerfile: dockerfile.health
    ports: ["8000:8000"]
    depends_on: [shamba-chatbot]

  ccs-dashboard:
    build:
      context: .
      dockerfile: dockerfile.dashboard
    ports: ["8001:8001"]
    depends_on: [ccs-health]

volumes:
  ollama_data:
